### ISSUE TITLE
Sync error with Bazel 0.26.1

### ISSUE THREAD

**Issue by senpo** [bazelbuild/tools_android#4]
```
ERROR: /Users/senpo/Sources/github/senpo/BUILD:51:23: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on genrule rule //java/com/google/aiux/dualcam:gen_google_services_xml_com_google_aiux_dualcam_google-services_json: 
Traceback (most recent call last):
	File "/Users/senpo/Sources/github/senpo/senpo-mono/workspace/java/com/google/aiux/dualcam/BUILD", line 51
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_senpo/8e8ab08dfe8b1ede4ab2e2dba795577f/external/intellij_aspect/intellij_info_bundled.bzl", line 53, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_senpo/8e8ab08dfe8b1ede4ab2e2dba795577f/external/intellij_aspect/intellij_info_impl.bzl", line 803, in intellij_info_aspect_impl
		update_set_in_dict(output_groups, "intellij-info-gene...", ...]))
	File "/private/var/tmp/_bazel_senpo/8e8ab08dfe8b1ede4ab2e2dba795577f/external/intellij_aspect/intellij_info_impl.bzl", line 200, in update_set_in_dict
		input_dict.get(key, depset()) | other_set
`|` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
```

With the standard usage of this tool:
```
TOOLS_ANDROID_VERSION = "0.1"
http_archive(
    name = "tools_android",
    strip_prefix = "tools_android-" + TOOLS_ANDROID_VERSION,
    url = "https://github.com/bazelbuild/tools_android/archive/%s.tar.gz" % TOOLS_ANDROID_VERSION,
)
load("@tools_android//tools/googleservices:defs.bzl", "google_services_workspace_dependencies")
google_services_workspace_dependencies()

load("@tools_android//tools/googleservices:defs.bzl", "google_services_xml")
GOOGLE_SERVICES_XML = google_services_xml(
    package_name = "com.google.aiux.dualcam",
    google_services_json = "google-services.json",
)
```

**Comment by ahumesky** [comment]
Thanks for the report, I assume that the issue in the intellij aspect was addressed long ago, if not we can reopen.
